### ISSUE TITLE
Add a user settings tab to allow users to change their passwords and other information about their accounts 

### ISSUE THREAD

**Issue by pro6dog** [yldbouk/dpwt#12]
Add a user settings tab that appears after sign-in that when click on will allow the user to change their password and other information about their account. For example, "email, password, username, and name"

**Comment by yldbouk** [comment]
also add option in users manager to reset password

**Comment by yldbouk** [comment]
fixed in 6eddb2ebccbc7dbeb794674d8ccd4dc56f7d974c
